### ISSUE TITLE
refreshed tabs should not have a hover state

### ISSUE THREAD

**Issue by Menkhaus-ge** [PredixDev/px-tabs#11]
## Expected behavior and actual behavior:
When a selected tab is hovered over it should not have a hover state. 

Light theme
![screen shot 2017-06-29 at 1 57 04 pm](https://user-images.githubusercontent.com/14931112/27709980-f4d18eec-5cd2-11e7-8041-6669d911ffc0.png)

on hover
![screen shot 2017-06-29 at 1 54 47 pm](https://user-images.githubusercontent.com/14931112/27709993-f9e305a0-5cd2-11e7-8b12-d8a5405869f7.png)

Dark theme
![screen shot 2017-06-29 at 1 54 13 pm](https://user-images.githubusercontent.com/14931112/27709999-fe71002c-5cd2-11e7-88eb-14ef86dac2ea.png)
 
on hover
![screen shot 2017-06-29 at 1 57 22 pm](https://user-images.githubusercontent.com/14931112/27710006-037e7978-5cd3-11e7-9eea-a84614cbb81b.png)

**Comment by randyaskin** [comment]
I removed the hover states when Hans removed them from the spec. Could you make sure you have the latest version of tabs and theme? and depending what repo this is, you may have to bower link it to itself (coz of px-demo) to make sure it's the latest.

**Comment by Menkhaus-ge** [comment]
Yeah my bad, my bower was out of date.
