### ISSUE TITLE
Default Tab selection does not work through a property

### ISSUE THREAD

**Issue by aditishete** [PredixDev/px-tabs#13]
# Submit an Issue
Here is my usage,

`<px-tabs  id='logTypesTabs' selected="{{selected}}" >
    <template id="logTypesTabsTemplate" is="dom-repeat" items="{{logTypes}}">
      <px-tab  id="{{item.fileName}}"> {{item.displayName}}</px-tab>
    </template>
 </px-tabs>`

My application uses angular and the controller sets the above properties on the $scope.
logTypes works fine and displays Tabs correctly. However, the default tab does not show until I click on it the first time. If I set, selected="0" it sets the first tab correctly. However, in my use case I need to change the tabs displayed. At that point I need to reset the selected tab back to the first one.

Any help/suggestions?

Aditi Shete

**Comment by mdwragg** [comment]
Hi,
Thanks for the issue. Can you show us the issue in a glitch or codepen? Perhaps we can help with it if we can play with a distilled/standalone example.
