### ISSUE TITLE
unable to install px-tabs giving error " ECONFLICT Unable to find suitable version for polymer"

### ISSUE THREAD

**Issue by Aanchal25** [PredixDev/px-tabs#5]
Error: cannot find the suitable version of polymer.
px-tabs require polymer 1.5.0 but not getting installed to this version.Present version of polymer in bower.json is 1.2.3

I need to update it because px-tabs is not working on internet 11.

**Comment by benoitjchevalier** [comment]
Which version are you trying to install? Version 0.4.1 of px-tabs includes Polymer 1.5.0 and bower install without error.

Looks like your conflict might come from another component requiring Polymer 1.2.3.

I'm closing this for now, feel free to reopen if you still think that is an issue.
