### ISSUE TITLE
Browser Compatibility Issue

### ISSUE THREAD

**Issue by RadhamaniK** [PredixDev/px-tabs#8]
Hi Team,

I am facing issues in rendering px-tab component in IE. Could anyone let me know the compatibility of the component with IE browser.

**Comment by randyaskin** [comment]
Can you be more specific? What issues? What version of Windows / IE?

I just tested in Sauce Labs and the tabs work fine in Windows 10/Edge and Windows 8/IE11.

**Comment by randyaskin** [comment]
Closing this due to non-responsiveness. Reopen if this is still an issue.
