### ISSUE TITLE
Error when we use Tab Control.

### ISSUE THREAD

**Issue by AdalbertoHenriquez** [PredixDev/px-tabs#9]
# Submit an Issue

Hi, 

I see the error below when i use tab control: 

Uncaught TypeError: Cannot set property 'selected' of null
    at index.html:203
    at webcomponents-lite.js:2484

Thanks,
Adalberto Henriquez

**Comment by runn-vermel** [comment]
HI @AdalbertoHenriquez 

I"m closing this issue - if you'd like to re-open it, please use our supplied issue template - and make sure to include some of your sample code.
